name: weather_base
description: Weather App by Flutter (HomeBase's take-home assignment)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  geocoding: ^2.1.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  location: ^4.2.0
  retrofit: ^4.0.3
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/